### PR TITLE
Also complete `#tags` and `^links`

### PR DESCRIPTION
**Pull request by aldur**
Thanks for the great plugin!

### CODE REVIEW

**Comment by crispgm** [comment]
image

it looks exceptions happened to me.

**Comment by aldur** [comment]
My bad, I made last minute changes and didn't test properly. Just fixed it.

**Comment by crispgm** [comment]
> My bad, I made last minute changes and didn't test properly. Just fixed it.

Looks good, would you mind providing me some use cases to test?

**Comment by aldur** [comment]
Sure! I tested the following on my beancount ledger:

1. Account completion should now work regardless of the line prefix, so you can test `2024-03-11 open Assets:xyz ...`, `balance`, and `close`.
2. Completion for tags should trigger as soon as hitting the `#` key (make sure you have a few transaction with tags)
3. Similarly for links, it should trigger by hitting `^`.

Also, the plugin doesn't "live reload" accounts/tags/links on a modified document (this was an existing behaviour).

If you want to force reload completions you can use the following ugly hack:

```lua
-- lua/plugins/beancount.lua
local M = {}

local cmp = require "cmp"

function M.reload_beancount_completions()
    for _, s in pairs(cmp.core.sources) do
        if s.name == "beancount" then
            s.source.items = nil
            print("Beancount completions will reload...")
        end
    end
end

return M
```

And then:

```vim
command -buffer ReloadCompletions w | lua require'plugins/beancount'.reload_beancount_completions()
```

**Comment by aldur** [comment]
Hi! Did you have a chance to test this?

**Comment by crispgm** [comment]
> Hi! Did you have a chance to test this?

I have issues with loading tags. The Python codes seemed work, but `vim.b.beancount_tags` is empty.

**Comment by aldur** [comment]
Can you provide the test case you are using?

**Comment by crispgm** [comment]
> Can you provide the test case you are using?

I use my daily beancount setup and added some tags. I think I may merge directly. But one more thing to be confirmed, I noticed that your completion item of account is now `cmp.lsp.CompletionItemKind.Interface`. Maybe we should keep all them as `cmp.lsp.CompletionItemKind.Property`?

**Comment by aldur** [comment]
Just pushed the change, thank you!

**Comment by crispgm** [comment]
@aldur Thanks!

**Pull request merged**
